import 'caregiver_task.dart';

class TasksRepository {
  static final TasksRepository instance = TasksRepository._();
  TasksRepository._();

  final List<CaregiverTask> _tasks = [
    // OVERDUE TASKS (8)
    CaregiverTask(
      id: '1',
      title: 'Medication Review',
      description: 'Review and update medication list for patient',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().subtract(const Duration(hours: 5)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '2',
      title: 'Follow-up Call',
      description: 'Call to check on recovery progress',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().subtract(const Duration(hours: 2)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '3',
      title: 'Update Care Plan',
      description: 'Review and update care plan based on recent visit',
      priority: TaskPriority.medium,
      status: TaskStatus.inProgress,
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      patientId: '3',
      patientName: 'Emma Williams',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    CaregiverTask(
      id: '6',
      title: 'Prescription Refill',
      description: 'Process prescription refill request',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().subtract(const Duration(hours: 8)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '10',
      title: 'Insurance Verification',
      description: 'Verify insurance coverage for upcoming procedure',
      priority: TaskPriority.high,
      status: TaskStatus.inProgress,
      dueDate: DateTime.now().subtract(const Duration(hours: 3)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '16',
      title: 'Pain Management Review',
      description: 'Assess pain levels and adjust medication plan',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().subtract(const Duration(hours: 12)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    CaregiverTask(
      id: '18',
      title: 'Specialist Referral',
      description: 'Send referral to cardiology for evaluation',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().subtract(const Duration(hours: 6)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '23',
      title: 'Fall Risk Assessment',
      description: 'Complete fall risk evaluation and safety plan',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().subtract(const Duration(hours: 4)),
      patientId: '4',
      patientName: 'David Nguyen',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),

    // DUE TODAY (8)
    CaregiverTask(
      id: '8',
      title: 'Blood Pressure Monitoring',
      description: 'Check and record blood pressure readings',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 1)),
      patientId: '3',
      patientName: 'Emma Williams',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    CaregiverTask(
      id: '12',
      title: 'Wound Care Assessment',
      description: 'Evaluate surgical wound healing progress',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 3)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    CaregiverTask(
      id: '14',
      title: 'Home Health Setup',
      description: 'Coordinate home health services for discharge',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 8)),
      patientId: '3',
      patientName: 'Emma Williams',
      createdAt: DateTime.now().subtract(const Duration(hours: 15)),
    ),
    CaregiverTask(
      id: '20',
      title: 'Glucose Monitoring Check',
      description: 'Review blood glucose logs and adjust insulin',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 2)),
      patientId: '3',
      patientName: 'Emma Williams',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    CaregiverTask(
      id: '28',
      title: 'Patient Education Review',
      description: 'Review discharge instructions with patient',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 5)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    CaregiverTask(
      id: '29',
      title: 'Care Coordination Call',
      description: 'Coordinate care with primary physician',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 6)),
      patientId: '4',
      patientName: 'David Nguyen',
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    CaregiverTask(
      id: '30',
      title: 'Lab Results Review',
      description: 'Review and interpret latest lab results',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 4)),
      patientId: '6',
      patientName: 'Robert King',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    CaregiverTask(
      id: '31',
      title: 'Mobility Assessment',
      description: 'Assess patient mobility and recommend aids',
      priority: TaskPriority.low,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(hours: 10)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),

    // COMPLETED TASKS (11)
    CaregiverTask(
      id: '7',
      title: 'Document Review',
      description: 'Review and sign off on medical documents',
      priority: TaskPriority.low,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      patientId: '6',
      patientName: 'Robert King',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      completedAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    CaregiverTask(
      id: '13',
      title: 'Immunization Record Update',
      description: 'Update patient immunization records in system',
      priority: TaskPriority.low,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(hours: 12)),
      patientId: '6',
      patientName: 'Robert King',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      completedAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    CaregiverTask(
      id: '17',
      title: 'Allergy Information Update',
      description: 'Review and update patient allergy records',
      priority: TaskPriority.low,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(days: 2)),
      patientId: '4',
      patientName: 'David Nguyen',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      completedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '24',
      title: 'Medication Reconciliation',
      description: 'Reconcile all medications after hospital discharge',
      priority: TaskPriority.high,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(hours: 4)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      completedAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    CaregiverTask(
      id: '27',
      title: 'Emergency Contact Verification',
      description: 'Verify and update emergency contact information',
      priority: TaskPriority.low,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(days: 3)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      completedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    CaregiverTask(
      id: '32',
      title: 'Initial Assessment Complete',
      description: 'Completed comprehensive patient assessment',
      priority: TaskPriority.high,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(days: 2)),
      patientId: '3',
      patientName: 'Emma Williams',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      completedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '33',
      title: 'Insurance Pre-Authorization',
      description: 'Obtained insurance approval for procedure',
      priority: TaskPriority.high,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      completedAt: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    CaregiverTask(
      id: '34',
      title: 'Follow-up Documentation',
      description: 'Documented follow-up visit notes',
      priority: TaskPriority.medium,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(hours: 20)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      completedAt: DateTime.now().subtract(const Duration(hours: 14)),
    ),
    CaregiverTask(
      id: '35',
      title: 'Nutrition Plan Review',
      description: 'Reviewed and approved dietary plan',
      priority: TaskPriority.medium,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      patientId: '4',
      patientName: 'David Nguyen',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      completedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '36',
      title: 'Care Team Meeting',
      description: 'Attended multidisciplinary care team meeting',
      priority: TaskPriority.low,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(days: 3)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      completedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    CaregiverTask(
      id: '37',
      title: 'Equipment Training',
      description: 'Completed training on new medical equipment',
      priority: TaskPriority.medium,
      status: TaskStatus.completed,
      dueDate: DateTime.now().subtract(const Duration(hours: 36)),
      patientId: '6',
      patientName: 'Robert King',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      completedAt: DateTime.now().subtract(const Duration(hours: 30)),
    ),

    // FUTURE TASKS (18)
    CaregiverTask(
      id: '4',
      title: 'Schedule Lab Work',
      description: 'Coordinate lab appointments for upcoming visit',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 2)),
      patientId: '4',
      patientName: 'David Nguyen',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    CaregiverTask(
      id: '5',
      title: 'Review Test Results',
      description: 'Analyze recent test results and update records',
      priority: TaskPriority.low,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 3)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    CaregiverTask(
      id: '9',
      title: 'Dietary Consultation',
      description: 'Schedule nutrition consultation appointment',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 1, hours: 3)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
    ),
    CaregiverTask(
      id: '11',
      title: 'Physical Therapy Referral',
      description: 'Submit referral for physical therapy evaluation',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 2)),
      patientId: '4',
      patientName: 'David Nguyen',
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    CaregiverTask(
      id: '15',
      title: 'Medical Equipment Order',
      description: 'Order DME supplies for patient home use',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 1, hours: 6)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(hours: 20)),
    ),
    CaregiverTask(
      id: '19',
      title: 'Transportation Arrangement',
      description: 'Arrange medical transport for upcoming appointment',
      priority: TaskPriority.medium,
      status: TaskStatus.inProgress,
      dueDate: DateTime.now().add(const Duration(days: 1)),
      patientId: '6',
      patientName: 'Robert King',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    CaregiverTask(
      id: '21',
      title: 'Advance Directive Discussion',
      description: 'Schedule discussion about advance care planning',
      priority: TaskPriority.low,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 4)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    CaregiverTask(
      id: '22',
      title: 'Vaccination Administration',
      description: 'Administer flu vaccine during next visit',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 1, hours: 8)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    CaregiverTask(
      id: '25',
      title: 'Caregiver Education Session',
      description: 'Provide training to family caregiver on care procedures',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 2, hours: 4)),
      patientId: '6',
      patientName: 'Robert King',
      createdAt: DateTime.now().subtract(const Duration(hours: 14)),
    ),
    CaregiverTask(
      id: '26',
      title: 'Mental Health Screening',
      description: 'Conduct depression and anxiety screening assessment',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 1, hours: 2)),
      patientId: '3',
      patientName: 'Emma Williams',
      createdAt: DateTime.now().subtract(const Duration(hours: 16)),
    ),
    CaregiverTask(
      id: '38',
      title: 'Quarterly Care Plan Review',
      description: 'Complete quarterly review of patient care plans',
      priority: TaskPriority.low,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 5)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
    ),
    CaregiverTask(
      id: '39',
      title: 'Chronic Disease Management',
      description: 'Review chronic disease management protocols',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 3, hours: 6)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    CaregiverTask(
      id: '40',
      title: 'Durable Medical Equipment Check',
      description: 'Inspect and verify DME functionality',
      priority: TaskPriority.low,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 6)),
      patientId: '3',
      patientName: 'Emma Williams',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    CaregiverTask(
      id: '41',
      title: 'Hospice Consultation',
      description: 'Arrange consultation with hospice services',
      priority: TaskPriority.high,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 2, hours: 8)),
      patientId: '4',
      patientName: 'David Nguyen',
      createdAt: DateTime.now().subtract(const Duration(hours: 14)),
    ),
    CaregiverTask(
      id: '42',
      title: 'Financial Assistance Review',
      description:
          'Review patient eligibility for financial assistance programs',
      priority: TaskPriority.low,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 7)),
      patientId: '5',
      patientName: 'Priya Patel',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    CaregiverTask(
      id: '43',
      title: 'Sleep Study Coordination',
      description: 'Coordinate sleep study appointment and preparation',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 4, hours: 2)),
      patientId: '6',
      patientName: 'Robert King',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    CaregiverTask(
      id: '44',
      title: 'Community Resource Connection',
      description: 'Connect patient with community support resources',
      priority: TaskPriority.low,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 8)),
      patientId: '1',
      patientName: 'Sarah Johnson',
      createdAt: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    CaregiverTask(
      id: '45',
      title: 'Occupational Therapy Evaluation',
      description: 'Schedule OT evaluation for activities of daily living',
      priority: TaskPriority.medium,
      status: TaskStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 3, hours: 12)),
      patientId: '2',
      patientName: 'Michael Chen',
      createdAt: DateTime.now().subtract(const Duration(hours: 22)),
    ),
  ];

  List<CaregiverTask> all() => List.unmodifiable(_tasks);

  List<CaregiverTask> pending() =>
      _tasks.where((t) => t.status != TaskStatus.completed).toList();

  List<CaregiverTask> completed() =>
      _tasks.where((t) => t.status == TaskStatus.completed).toList();

  List<CaregiverTask> sortedByPriorityAndDate() {
    final tasks = pending();
    tasks.sort((a, b) {
      // First sort by priority (high -> medium -> low)
      final priorityOrder = {
        TaskPriority.high: 0,
        TaskPriority.medium: 1,
        TaskPriority.low: 2,
      };
      final priorityCompare = priorityOrder[a.priority]!.compareTo(
        priorityOrder[b.priority]!,
      );
      if (priorityCompare != 0) return priorityCompare;

      // Then by due date (earliest first)
      return a.dueDate.compareTo(b.dueDate);
    });
    return tasks;
  }

  List<CaregiverTask> overdue() => _tasks.where((t) => t.isOverdue).toList();

  List<CaregiverTask> dueToday() => _tasks.where((t) => t.isDueToday).toList();

  void toggleComplete(String taskId) {
    final index = _tasks.indexWhere((t) => t.id == taskId);
    if (index != -1) {
      final task = _tasks[index];
      _tasks[index] = task.copyWith(
        status: task.status == TaskStatus.completed
            ? TaskStatus.pending
            : TaskStatus.completed,
        completedAt: task.status == TaskStatus.completed
            ? null
            : DateTime.now(),
      );
    }
  }

  void updateStatus(String taskId, TaskStatus status) {
    final index = _tasks.indexWhere((t) => t.id == taskId);
    if (index != -1) {
      _tasks[index] = _tasks[index].copyWith(
        status: status,
        completedAt: status == TaskStatus.completed ? DateTime.now() : null,
      );
    }
  }
}
